### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by zactimeinc** [lincheney/journald-2-cloudwatch#2]
Could you add a license, please?  I'd like to use this on a private project, if you are open to that.  Also, I have some changes to the docker file which you might want to consider, not sure how you are using.

**Comment by lincheney** [comment]
License added in https://github.com/lincheney/journald-2-cloudwatch/commit/821fe42f195524564b7b2188ca72a6f30255f103

@zactimeinc 
I have no problems with private use.
If you have any changes you want to suggest, just open another issue or PR.
