### ISSUE TITLE
Require images for ARM64

### ISSUE THREAD

**Issue by odidev** [lincheney/journald-2-cloudwatch#27]
Hi Team,

I am trying to use this image on the arm64 platform, but it seems it does not have an arm64 supported tag available in the docker hub.

I have built the image successfully in travis-CI on both amd64 and arm64 platform but I am getting the below error while installing moto in **Dockerfile.test**:
```
Collecting cryptography>=3.3.1 (from moto)
  Could not find a version that satisfies the requirement cryptography>=3.3.1 (from moto) (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1)
No matching distribution found for cryptography>=3.3.1 (from moto)
The command '/bin/sh -c pip3 --no-cache-dir install moto coverage coveralls' returned a non-zero code: 1
```
Do you have any plans in releasing arm64 images?

If interested, I will add changes in Travis-CI and raise a PR for the same.

**Comment by lincheney** [comment]
hello! I wasn't explicitly planning on having arm64 support, but I would totally take a PR.

**Comment by odidev** [comment]
I have updated Dockerfile base image tag and added arm64 tag and tested the build and it is working fine in both platforms.
Please check [this report](https://travis-ci.com/github/pruthvireddypuresoftware/journald-2-cloudwatch/builds/223589663) for more details. 

**Changes required:** https://github.com/odidev/journald-2-cloudwatch/commit/002e010d3c495a1b58d32df08076366101d155fc

May I know how are you releasing images to docker hub?

If the changes look good, I will raise a PR.

**Comment by lincheney** [comment]
hi
That looks good, can you submit a PR?
I honestly can't remember how I pushed images to docker hub, it's been so long since I worked on this repo, I'll have to figure it out

**Comment by odidev** [comment]
@lincheney,
Please check #28 and let me know your feedback.

**Comment by lincheney** [comment]
ARM64 now available :)
https://hub.docker.com/r/lincheney/journald-2-cloudwatch/tags
